### ISSUE TITLE
Update to 2.11

### ISSUE THREAD

**Issue by adrianknight89** [Baseflow/ExoPlayerXamarin#99]
## 🏗 Enhancement Proposal

Currently, I see that the `ExtractorMediaSource` constructor is deprecated, and I can't use `ProgressiveMediaSource` because it exists in a newer version. Also, your sample code needs to be updated on the homepage since it looks like `ProgressiveMediaSource` is being preferred.

https://exoplayer.dev/hello-world.html

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by JohnGalt1717** [comment]
I also would like to request this. The current version has major issues with Azure Media Services HLS which has been fixed in the most recent versions of exoPlayer.  Specifically it doesn't buffer properly which causes stuttering.

Here's the issue I opened with them: https://github.com/google/ExoPlayer/issues/6844

**Comment by martijn00** [comment]
@adrianknight89 I've started some work on this, but could use some help to get everything updated. Would it be possible to help with some PR's?

**Comment by mr5z** [comment]
@martijn00 I'll try to help. Do you have something in mind I can work with?

**Comment by martijn00** [comment]
@mr5z Just pull in the latest from develop and try compile. There are metadata fixes that need to be done to be able to build.

**Comment by martijn00** [comment]
It's done.
